name: Build Yoru Optimized

on:
  push:
    branches: [ "main" ]   # runs when you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: gradle build --no-daemon

      - name: List build output (debug)
        run: ls -la build/libs || true

      - name: Upload mod JAR
        uses: actions/upload-artifact@v4
        with:
          name: yoru-optimized
          path: build/libs/*.jar
