name: Build Yoru Optimized

on:
  push:
    branches: [ "main" ]   # Runs whenever you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: gradle build

      - name: Upload mod JAR
        uses: actions/upload-artifact@v3
        with:
          name: yoru-optimized
          path: build/libs/*.jar
